// Generated by gencpp from file counter_node/counterResponse.msg
// DO NOT EDIT!


#ifndef COUNTER_NODE_MESSAGE_COUNTERRESPONSE_H
#define COUNTER_NODE_MESSAGE_COUNTERRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace counter_node
{
template <class ContainerAllocator>
struct counterResponse_
{
  typedef counterResponse_<ContainerAllocator> Type;

  counterResponse_()
    : reply(0.0)  {
    }
  counterResponse_(const ContainerAllocator& _alloc)
    : reply(0.0)  {
  (void)_alloc;
    }



   typedef float _reply_type;
  _reply_type reply;





  typedef boost::shared_ptr< ::counter_node::counterResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::counter_node::counterResponse_<ContainerAllocator> const> ConstPtr;

}; // struct counterResponse_

typedef ::counter_node::counterResponse_<std::allocator<void> > counterResponse;

typedef boost::shared_ptr< ::counter_node::counterResponse > counterResponsePtr;
typedef boost::shared_ptr< ::counter_node::counterResponse const> counterResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::counter_node::counterResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::counter_node::counterResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::counter_node::counterResponse_<ContainerAllocator1> & lhs, const ::counter_node::counterResponse_<ContainerAllocator2> & rhs)
{
  return lhs.reply == rhs.reply;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::counter_node::counterResponse_<ContainerAllocator1> & lhs, const ::counter_node::counterResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace counter_node

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::counter_node::counterResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::counter_node::counterResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::counter_node::counterResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::counter_node::counterResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::counter_node::counterResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::counter_node::counterResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::counter_node::counterResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "040d3b0e975a8d9d7be9e89146cbb7a9";
  }

  static const char* value(const ::counter_node::counterResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x040d3b0e975a8d9dULL;
  static const uint64_t static_value2 = 0x7be9e89146cbb7a9ULL;
};

template<class ContainerAllocator>
struct DataType< ::counter_node::counterResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "counter_node/counterResponse";
  }

  static const char* value(const ::counter_node::counterResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::counter_node::counterResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 reply\n"
;
  }

  static const char* value(const ::counter_node::counterResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::counter_node::counterResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.reply);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct counterResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::counter_node::counterResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::counter_node::counterResponse_<ContainerAllocator>& v)
  {
    s << indent << "reply: ";
    Printer<float>::stream(s, indent + "  ", v.reply);
  }
};

} // namespace message_operations
} // namespace ros

#endif // COUNTER_NODE_MESSAGE_COUNTERRESPONSE_H
